name: UnitedClans
version: '${project.version}'
main: unitedclans.UnitedClans
api-version: '1.20'
authors: [MouseJava]
softdepend: [PlaceholderAPI]
description: The plugin implements the clan system in Minecraft

permissions:
  unitedclans.uchelp:
    description: Permission to use command uchelp
    default: true
  unitedclans.ucreloadconfig:
    description: Permission to use command ucreloadconfig
    default: op
  unitedclans.ucinfo:
    description: Permission to use command ucinfo
    default: true
  unitedclans.uccreate:
    description: Permission to use command uccreate
    default: true
  unitedclans.ucdelete:
    description: Permission to use command ucdelete
    default: true
  unitedclans.ucinvite:
    description: Permission to use command ucinvite
    default: true
  unitedclans.ucaccept:
    description: Permission to use command ucaccept
    default: true
  unitedclans.uckick:
    description: Permission to use command uckick
    default: true
  unitedclans.ucleave:
    description: Permission to use command ucleave
    default: true
  unitedclans.ucsetrole:
    description: Permission to use command ucsetrole
    default: true
  unitedclans.ucmenu:
    description: Permission to use command ucmenu
    default: true
  unitedclans.ucchat:
    description: Permission to use command ucchat
    default: true
  unitedclans.ucchangeleader:
    description: Permission to use command ucchangeleader
    default: true
  unitedclans.ucbankdeposit:
    description: Permission to use command ucbankdeposit
    default: true
  unitedclans.ucbankwithdraw:
    description: Permission to use command ucbankwithdraw
    default: true
  unitedclans.uctop:
    description: Permission to use command uctop
    default: true
  unitedclans.ucletter:
    description: Permission to use command ucletter
    default: true
